name: topaz-dev
services:
  topaz-dev-db:
    image: postgres:latest
    container_name: topaz-dev-db
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: elizielx
      POSTGRES_PASSWORD: elizielx
      POSTGRES_DB: topaz
    volumes:
      - topaz_postgres_data:/var/lib/postgresql/data
    networks:
      - topaz-dev-network
volumes:
  topaz_postgres_data:
    name: topaz_postgres_data
networks:
  topaz-dev-network:
    driver: bridge
