import {
  MdxBlockquote,
  MdxCode,
  MdxDivider,
  MdxH1,
  MdxH2,
  MdxH3,
  MdxH4,
  MdxH5,
  MdxH6,
  MdxLink,
  MdxListItem,
  MdxOrderedList,
  MdxParagraph,
  MdxPre,
  MdxStrong,
  MdxTable,
  MdxTableBody,
  MdxTableCell,
  MdxTableHead,
  MdxTableHeadCell,
  MdxUnorderedList,
} from "./mdx-components";

export const mdxComponents = {
  a: MdxLink,
  blockquote: MdxBlockquote,
  code: MdxCode,
  h1: MdxH1,
  h2: MdxH2,
  h3: MdxH3,
  h4: MdxH4,
  h5: MdxH5,
  h6: MdxH6,
  hr: MdxDivider,
  li: MdxListItem,
  ol: MdxOrderedList,
  p: MdxParagraph,
  pre: MdxPre,
  strong: MdxStrong,
  table: MdxTable,
  tbody: MdxTableBody,
  td: MdxTableCell,
  th: MdxTableHeadCell,
  thead: MdxTableHead,
  ul: MdxUnorderedList,
};
